### ISSUE TITLE
{} creates empty set instead of dict

### ISSUE THREAD

**Issue by Oberacda** [fzi-forschungszentrum-informatik/ros2_ros_bt_py#3]
When creating a new node in the web editor that has options the folliwng error appears:
```bash
[tree_node-1] Traceback (most recent call last):
[tree_node-1]   File "/home/doberacker/repos/ros_ws/ros2_ros_bt_py/colcon_ws/install/ros_bt_py/lib/ros_bt_py/tree_node", line 33, in <module>
[tree_node-1]     sys.exit(load_entry_point('ros-bt-py==0.1.0', 'console_scripts', 'tree_node')())
[tree_node-1]   File "/home/doberacker/repos/ros_ws/ros2_ros_bt_py/colcon_ws/install/ros_bt_py/lib/python3.10/site-packages/ros_bt_py/tree_node.py", line 424, in main
[tree_node-1]     executor.spin()
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 279, in spin
[tree_node-1]     self.spin_once()
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 764, in spin_once
[tree_node-1]     self._spin_once_impl(timeout_sec)
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 761, in _spin_once_impl
[tree_node-1]     future.result()
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
[tree_node-1]     raise self.exception()
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[tree_node-1]     self._handler.send(None)
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
[tree_node-1]     await call_coroutine(entity, arg)
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 372, in _execute_service
[tree_node-1]     response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
[tree_node-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[tree_node-1]     return callback(*args)
[tree_node-1]   File "/home/doberacker/repos/ros_ws/ros2_ros_bt_py/colcon_ws/install/ros_bt_py/lib/python3.10/site-packages/ros_bt_py/tree_manager.py", line 105, in service_handler
[tree_node-1]     return func(self, request, response, **kwds)
[tree_node-1]   File "/home/doberacker/repos/ros_ws/ros2_ros_bt_py/colcon_ws/install/ros_bt_py/lib/python3.10/site-packages/ros_bt_py/tree_manager.py", line 1655, in set_options
[tree_node-1]     for key, value in deserialized_options.items():
[tree_node-1] AttributeError: 'set' object has no attribute 'items'
[tree_node-1] The following exception was never retrieved: cannot use Destroyable because destruction was requested
```

**Comment by Oberacda** [comment]
Fixed in d5b24b922bbbd9e177aa2d93199ac7dd362b7d57
